/*
package com.example.spring_dingshi.other;





public class TestApi {
    ZBCXH,ZGYSM,ERSDA,LAEDA,LVORM,ZZTAI,ZCAND,ZCDDW,ZKUAN,ZKDDW,ZWXCC,ZSHHD,ZBANH,ZBHGC,ZTONH,ZXTON,ZTBLE,ZXTBL,ZBLBZ,ZYANS,ZSFKB,ZBLDJ,ZBJZT,ZTBRA,ZTBR1,ZTBZA,ZTBRZ,ZTBCC,ZSZHL,ZHDSS,ZDUDW,ZBLHD,ZSZLD




    #{ZBCXH},#{ZGYSM},#{ERSDA},#{LAEDA},#{LVORM},#{ZZTAI},#{ZCAND},#{ZCDDW},#{ZKUAN},#{ZKDDW},#{ZWXCC},#{ZSHHD},#{ZBANH},#{ZBHGC},#{ZTONH},#{ZXTON},#{ZTBLE},#{ZXTBL},#{ZBLBZ},#{ZYANS},#{ZSFKB},#{ZBLDJ},#{ZBJZT},#{ZTBRA},#{ZTBR1},#{ZTBZA},#{ZTBRZ},#{ZTBCC},#{ZSZHL},#{ZHDSS},#{ZDUDW},#{ZBLHD},#{ZSZLD}

    ZBCXH=#{ZBCXH},ZGYSM=#{ZGYSM},ERSDA=#{ERSDA},LAEDA=#{LAEDA},LVORM=#{LVORM},ZZTAI=#{ZZTAI},ZCAND=#{ZCAND},ZCDDW=#{ZCDDW},ZKUAN=#{ZKUAN},ZKDDW=#{ZKDDW},ZWXCC=#{ZWXCC},ZSHHD=#{ZSHHD},ZBANH=#{ZBANH},ZBHGC=#{ZBHGC},ZTONH=#{ZTONH},ZXTON=#{ZXTON},ZTBLE=#{ZTBLE},ZXTBL=#{ZXTBL},ZBLBZ=#{ZBLBZ},ZYANS=#{ZYANS},ZSFKB=#{ZSFKB},ZBLDJ=#{ZBLDJ},ZBJZT=#{ZBJZT},ZTBRA=#{ZTBRA},ZTBR1=#{ZTBR1},ZTBZA=#{ZTBZA},ZTBRZ=#{ZTBRZ},ZTBCC=#{ZTBCC},ZSZHL=#{ZSZHL},ZHDSS=#{ZHDSS},ZDUDW=#{ZDUDW},ZBLHD=#{ZBLHD},ZSZLD=#{ZSZLD}



    ZDKSS,ZDK02,ZDK03,ZDK04,ZDK05,ZDK06,ZDK07,ZDK08,ZDK09,ZDK10,ZDK15,ZDK20,ZDFSS,ZDF02,ZDF03,ZDF04,ZDF05,ZDF06,ZDF07,ZDF08,ZDF09,ZDF10,ZDF15,ZDF20


  #{ZDKSS},#{ZDK02},#{ZDK03},#{ZDK04},#{ZDK05},#{ZDK06},#{ZDK07},#{ZDK08},#{ZDK09},#{ZDK10},#{ZDK15},#{ZDK20},#{ZDFSS},#{ZDF02},#{ZDF03},#{ZDF04},#{ZDF05},#{ZDF06},#{ZDF07},#{ZDF08},#{ZDF09},#{ZDF10},#{ZDF15},#{ZDF20}

  ZDKSS=#{ZDKSS},ZDK02=#{ZDK02},ZDK03=#{ZDK03},ZDK04=#{ZDK04},ZDK05=#{ZDK05},ZDK06=#{ZDK06},ZDK07=#{ZDK07},ZDK08=#{ZDK08},ZDK09=#{ZDK09},ZDK10=#{ZDK10},ZDK15=#{ZDK15},ZDK20=#{ZDK20},ZDFSS=#{ZDFSS},ZDF02=#{ZDF02},ZDF03=#{ZDF03},ZDF04=#{ZDF04},ZDF05=#{ZDF05},ZDF06=#{ZDF06},ZDF07=#{ZDF07},ZDF08=#{ZDF08},ZDF09=#{ZDF09},ZDF10=#{ZDF10},ZDF15=#{ZDF15},ZDF20=#{ZDF20}






}
*/
