#spring:
  #datasource:
    #url: jdbc:mysql://localhost:3306/sap?&useSSL=false&serverTimezone=UTC
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #username: root
    #password: admin

spring:
  datasource:
    url: jdbc:sqlserver://192.168.0.48:1433;databaseName=sap_basic_info
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: kbdyn2015



mybatis:
  type-aliases-package: com.example.spring_dingshi.entity
server:
  port: 8089


logging:
  config: classpath:log4j.xml


